/**
 * agentEngine.js
 *
 * Agentic research engine for Science Bots.
 *
 * Pipeline:
 *   Orchestrator → Researcher → Analyzer → Researcher → Analyzer
 *                → Writer → Reviewer → Writer → Reviewer → DONE
 *
 * Source retrieval is delegated to researchProvider, which selects the
 * implementation based on the RESEARCH_MODE environment variable:
 *   demo  — deterministic demo data (default)
 *   real  — real research APIs (Phase 4)
 *
 * The external event contract (SSE schema, agent IDs, event types) is
 * unchanged regardless of provider.
 *
 * Target runtime in demo mode: 30–50 seconds.
 */

import {
  createEvent,
  emit,
  EVENT_TYPES,
  AGENT_IDS,
  AGENT_STATES,
} from './eventService.js';

import {
  getResearch,
  updateResearch,
  updateAgent,
  addSource,
  addClaim,
  setPaper,
  appendEvent,
  RESEARCH_STATUS,
} from './researchService.js';

import { search as providerSearch } from './research/researchProvider.js';
import { analyzeClaims } from './analyzerService.js';

// ─── Utility ──────────────────────────────────────────────────────────────────

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * Emit a canonical event AND persist it to the session event log.
 */
function fire(researchId, opts) {
  const event = createEvent(opts);
  appendEvent(researchId, event);
  emit(researchId, event);
  return event;
}

/**
 * Update an agent's in-memory state and emit an agent_update event.
 */
async function agentUpdate(researchId, agentId, state, action, message, payload = {}) {
  updateAgent(researchId, agentId, { state, action, message });
  updateResearch(researchId, { currentAgent: agentId });
  fire(researchId, {
    type:    EVENT_TYPES.AGENT_UPDATE,
    agent:   agentId,
    status:  state,
    action,
    message,
    payload,
  });
}

/**
 * Mark the from-agent as waiting and emit a handoff event.
 */
async function handoff(researchId, fromAgent, toAgent, message) {
  updateAgent(researchId, fromAgent, { state: AGENT_STATES.WAITING, action: 'waiting', message: null });
  fire(researchId, {
    type:    EVENT_TYPES.HANDOFF,
    agent:   fromAgent,
    status:  AGENT_STATES.WAITING,
    action:  'handoff',
    message: message ?? `Handing off from ${fromAgent} to ${toAgent}.`,
    to:      toAgent,
    payload: { from: fromAgent, to: toAgent },
  });
  await delay(600);
}

// ─── Paper builder (engine-level — not provider concern) ─────────────────────

function buildClaims(topic, sourceIds, nextClmId) {
  return [
    {
      id:          nextClmId(),
      text:        `[DEMO] The primary domain of "${topic}" has demonstrated measurable impact across recent literature.`,
      status:      'pending',
      sourceIds:   [sourceIds[0]],
      evidenceIds: [sourceIds[0] ? `ev_${sourceIds[0]}` : 'ev_demo_1'],
    },
    {
      id:          nextClmId(),
      text:        `[DEMO] Existing methodologies show significant variation in outcomes related to "${topic}".`,
      status:      'pending',
      sourceIds:   [sourceIds[1]],
      evidenceIds: [sourceIds[1] ? `ev_${sourceIds[1]}` : 'ev_demo_2'],
    },
    {
      id:          nextClmId(),
      text:        `[DEMO] Current research gaps indicate opportunities for further investigation into "${topic}".`,
      status:      'pending',
      sourceIds:   [sourceIds[0], sourceIds[2] ?? sourceIds[1]],
      evidenceIds: [sourceIds[0] ? `ev_${sourceIds[0]}` : 'ev_demo_1', sourceIds[2] ? `ev_${sourceIds[2]}` : 'ev_demo_3'],
    },
  ];
}

function buildPaper(topic, sources, claims, isRevised, isDemo = false) {
  const refs = sources.map((s, i) =>
    isDemo
      ? `[DEMO Ref ${i + 1}] ${(s.authors || ['Demo, A.']).join(', ')} (${s.year || 2024}). "${s.title}". Demo Source.`
      : `[Ref ${i + 1}] "${s.title}". ${s.domain || 'Academic Source'} (${s.sourceType || 'academic'}). ${s.url}`
  );

  return {
    title:        isDemo ? `[DEMO] ${topic}: A Systematic Analysis` : `${topic}: A Systematic Analysis`,
    abstract:
      (isDemo ? `[DEMO PAPER] ` : '') +
      `This paper presents a systematic analysis of "${topic}". ` +
      `Conducted by the Science Bots autonomous agent system${isDemo ? ' in demo mode' : ''}. ` +
      (isDemo ? `All sources and findings are clearly marked as demo data. ` : `Synthesises evidence from ${sources.length} sources. `) +
      (isRevised
        ? 'This is the revised version incorporating reviewer feedback.'
        : 'This is the initial draft pending final review.'),
    introduction:
      (isDemo ? `[DEMO] ` : '') +
      `The field of "${topic}" has attracted significant scholarly attention. ` +
      `This research synthesises available evidence to provide a structured overview of key ` +
      `findings, methodologies, and future directions.` +
      (isDemo ? ` NOTE: All content is generated by the Science Bots demo engine and does not represent real research.` : ''),
    findings: isDemo
      ? [
          {
            heading: '[DEMO] Finding 1: Core Trends',
            content:
              `Analysis of demo sources indicates a consistent pattern of development in "${topic}". ` +
              `[DEMO Source 1] provides foundational evidence supporting this observation.`,
          },
          {
            heading: '[DEMO] Finding 2: Methodological Approaches',
            content:
              `Multiple demo sources document varied methodological approaches. ` +
              `[DEMO Source 2] highlights empirical results that align with theoretical frameworks.`,
          },
          {
            heading: isRevised
              ? '[DEMO] Finding 3: Expanded Evidence (Revised)'
              : '[DEMO] Finding 3: Research Gaps',
            content: isRevised
              ? `Following reviewer feedback, this section has been strengthened with explicit reference ` +
                `to [DEMO Source 4], which directly supports the key claim regarding research gaps.`
              : `Current demo evidence identifies key research gaps warranting further exploration.`,
          },
        ]
      : claims.slice(0, 3).map((c, i) => {
          const isTargetedRevision = isRevised && (i === 2 || i === claims.length - 1);
          const statusLabel = c.status === 'supported'
            ? 'SUPPORTED'
            : c.status === 'conflict'
            ? 'CONFLICT'
            : 'INSUFFICIENT EVIDENCE / UNVERIFIED';
          return {
            heading: `Finding ${i + 1}: ${c.text.substring(0, 50)}...`,
            content: `${c.text}\nEvidence Assessment (${statusLabel}, ${Math.round((c.confidence || 0.8) * 100)}% confidence): ${c.summary || (c.status === 'supported' ? 'Corroborated by literature.' : 'Evidence is insufficient or indirect.')} [Cited Source IDs: ${(c.sourceIds || []).join(', ') || 'Literature'}]` +
              (isTargetedRevision
                ? `\n\n[Revised following reviewer verification: Evidence cross-referenced with ${sources.length} retrieved scholarly sources and citations re-validated.]`
                : ''),
          };
        }),
    analysis:
      (isDemo ? `[DEMO] ` : '') +
      `The convergence of evidence from ${sources.length} sources supports the conclusion ` +
      `that "${topic}" is an actively evolving field with significant implications. ` +
      (isRevised
        ? 'Reviewer feedback has been incorporated to strengthen all key claims.'
        : 'Initial analysis subject to revision based on reviewer feedback.'),
    conclusion:
      (isDemo ? `[DEMO] ` : '') +
      `This systematic analysis demonstrates the Science Bots autonomous research workflow. ` +
      `The agentic pipeline — Orchestrator → Researcher → Analyzer → Writer → Reviewer — ` +
      `has successfully evaluated evidence and synthesised findings for: "${topic}".`,
    references: refs,
    claims:     claims,
    metadata: {
      generatedAt:  new Date().toISOString(),
      agentSystem:  isDemo ? 'Science Bots v1.0 (Demo Mode)' : 'Science Bots v1.0 (Real Research)',
      topic,
      sourceCount:  sources.length,
      claimCount:   claims.filter((c) => c.status === 'supported').length,
      isRevised,
      demo:         isDemo,
    },
  };
}

// ─── Claim builder (analyzer-level — not provider concern) ───────────────────

function makeClaimId() {
  return `clm_${crypto.randomUUID().replace(/-/g, '')}`;
}

// ─── Main workflow ────────────────────────────────────────────────────────────

async function runWorkflow(researchId, topic) {
  const nextClmId = makeClaimId;

  // Mark session as running
  updateResearch(researchId, { status: RESEARCH_STATUS.RUNNING });

  // ══════════════════════════════════════════════════════════════════════
  // STEP 1 — ORCHESTRATOR: plan and route to researcher
  // ══════════════════════════════════════════════════════════════════════
  await delay(800);
  await agentUpdate(researchId, AGENT_IDS.ORCHESTRATOR, AGENT_STATES.WORKING,
    'planning', 'Planning the research workflow...');
  await delay(1400);

  await agentUpdate(researchId, AGENT_IDS.ORCHESTRATOR, AGENT_STATES.WORKING,
    'routing', 'Routing to Researcher agent to begin evidence gathering.');
  await delay(800);

  await handoff(researchId, AGENT_IDS.ORCHESTRATOR, AGENT_IDS.RESEARCHER,
    'Orchestrator → Researcher: Begin initial evidence search.');

  // ══════════════════════════════════════════════════════════════════════
  // STEP 2 — RESEARCHER: first pass (3 sources)
  // ══════════════════════════════════════════════════════════════════════
  await agentUpdate(researchId, AGENT_IDS.RESEARCHER, AGENT_STATES.WORKING,
    'searching', 'Searching academic sources...');
  await delay(1500);

  await agentUpdate(researchId, AGENT_IDS.RESEARCHER, AGENT_STATES.TOOL_CALLING,
    'fetching', 'Retrieving source metadata...');
  await delay(1000);

  // Delegate to the configured research provider (demo or real)
  const providerResult = await providerSearch({
    topic,
    existingSources: [],
    pass: 'initial',
  });

  const {
    sources: initialSources = [],
    claims: initialClaims = [],
    usedFallback = false,
    mode = 'demo',
    error: providerError,
    fallbackReason,
  } = providerResult;

  // Real mode only if provider was real AND did not fallback to demo
  const isDemo = mode === 'demo' || usedFallback;

  if (usedFallback) {
    console.warn(`[AgentEngine] Real search failed (${fallbackReason}), fallback to demo activated.`);
    fire(researchId, {
      type:    EVENT_TYPES.AGENT_UPDATE,
      agent:   AGENT_IDS.RESEARCHER,
      status:  AGENT_STATES.WORKING,
      action:  'fallback_to_demo',
      message: `Real research provider failed (${fallbackReason || 'error'}). Safely falling back to demo mode.`,
      payload: { fallback: true, reason: fallbackReason },
    });
  }

  // If real mode and no sources were returned, fail honestly without fabricating demo data
  if (!isDemo && initialSources.length === 0) {
    const errorMsg = providerError
      ? `Real research provider failed: ${providerError}`
      : `No scholarly sources found on OpenAlex for topic: "${topic}".`;

    console.warn(`[AgentEngine] Real search returned 0 sources for session ${researchId}: ${errorMsg}`);
    await agentUpdate(researchId, AGENT_IDS.RESEARCHER, AGENT_STATES.ERROR,
      'search_failed', errorMsg);

    updateResearch(researchId, {
      status:       RESEARCH_STATUS.ERROR,
      currentAgent: null,
    });

    fire(researchId, {
      type:    EVENT_TYPES.ERROR,
      agent:   AGENT_IDS.RESEARCHER,
      status:  AGENT_STATES.ERROR,
      action:  'no_sources_found',
      message: errorMsg,
      payload: { topic, error: providerError ?? 'Zero sources returned' },
    });
    return;
  }

  for (const source of initialSources) {
    addSource(researchId, source);
    fire(researchId, {
      type:    EVENT_TYPES.SOURCE_FOUND,
      agent:   AGENT_IDS.RESEARCHER,
      status:  AGENT_STATES.WORKING,
      action:  'source_found',
      message: `Found source: "${source.title}"`,
      payload: source,
    });
    await delay(700);
  }

  await agentUpdate(researchId, AGENT_IDS.RESEARCHER, AGENT_STATES.COMPLETED,
    'search_complete',
    isDemo
      ? `Initial search complete. Found ${initialSources.length} demo sources.`
      : `Initial search complete. Found ${initialSources.length} external sources.`);
  await delay(700);

  await handoff(researchId, AGENT_IDS.RESEARCHER, AGENT_IDS.ANALYZER,
    'Researcher → Analyzer: Initial sources ready for evaluation.');

  let claims = [];

  if (isDemo) {
    // ══════════════════════════════════════════════════════════════════════
    // DEMO MODE: Deterministic 49-event workflow execution
    // ══════════════════════════════════════════════════════════════════════
    await agentUpdate(researchId, AGENT_IDS.ANALYZER, AGENT_STATES.VERIFYING,
      'evaluating_evidence', 'Evaluating evidence and checking claims...');
    await delay(1500);

    await agentUpdate(researchId, AGENT_IDS.ANALYZER, AGENT_STATES.VERIFYING,
      'cross_referencing', 'Cross-referencing sources for consistency...');
    await delay(1200);

    // Intentional feedback loop #1 — insufficient evidence
    fire(researchId, {
      type:    EVENT_TYPES.INSUFFICIENT_EVIDENCE,
      agent:   AGENT_IDS.ANALYZER,
      status:  AGENT_STATES.VERIFYING,
      action:  'insufficient_evidence',
      message: 'Additional evidence is required for one key claim.',
      payload: {
        claim: 'Research gap analysis (Finding 3) requires a stronger supporting source.',
      },
    });
    await delay(1000);

    // Orchestrator re-routes
    await agentUpdate(researchId, AGENT_IDS.ORCHESTRATOR, AGENT_STATES.WORKING,
      'rerouting',
      'Orchestrator: Insufficient evidence detected — rerouting to Researcher for additional search.');
    await delay(700);

    await handoff(researchId, AGENT_IDS.ANALYZER, AGENT_IDS.RESEARCHER,
      'Analyzer → Researcher: Please expand the search with supplementary evidence.');

    // STEP 4 — RESEARCHER: second pass (1 supplementary source)
    await agentUpdate(researchId, AGENT_IDS.RESEARCHER, AGENT_STATES.WORKING,
      'searching', 'Searching for additional supporting evidence...');
    await delay(1400);

    const currentSourcesSnap = getResearch(researchId)?.sources ?? [];
    const { sources: suppSources } = await providerSearch({
      topic,
      existingSources: currentSourcesSnap,
      pass: 'supplementary',
    });

    for (const suppSource of suppSources) {
      addSource(researchId, suppSource);
      fire(researchId, {
        type:    EVENT_TYPES.SOURCE_FOUND,
        agent:   AGENT_IDS.RESEARCHER,
        status:  AGENT_STATES.WORKING,
        action:  'source_found',
        message: `Found supplementary source: "${suppSource.title}"`,
        payload: suppSource,
      });
      await delay(700);
    }

    await agentUpdate(researchId, AGENT_IDS.RESEARCHER, AGENT_STATES.COMPLETED,
      'search_complete', 'Supplementary search complete. Additional source located.');
    await delay(700);

    await handoff(researchId, AGENT_IDS.RESEARCHER, AGENT_IDS.ANALYZER,
      'Researcher → Analyzer: Expanded source set ready for re-evaluation.');

    // STEP 5 — ANALYZER: second pass → claims verified
    await agentUpdate(researchId, AGENT_IDS.ANALYZER, AGENT_STATES.VERIFYING,
      'validating', 'Validating the expanded evidence set...');
    await delay(1400);

    await agentUpdate(researchId, AGENT_IDS.ANALYZER, AGENT_STATES.VERIFYING,
      'building_claims', 'Building and verifying claims from all sources...');
    await delay(1200);

    const allCollectedSources = getResearch(researchId)?.sources ?? [];
    const allSourceIds = allCollectedSources.map((s) => s.id);
    claims = buildClaims(topic, allSourceIds, nextClmId);

    for (const claim of claims) {
      claim.status = 'supported';
      addClaim(researchId, claim);
      fire(researchId, {
        type:    EVENT_TYPES.CLAIM_VERIFIED,
        agent:   AGENT_IDS.ANALYZER,
        status:  AGENT_STATES.VERIFYING,
        action:  'claim_verified',
        message: `Claim verified: "${claim.text.substring(0, 80)}…"`,
        payload: claim,
      });
      await delay(700);
    }

    await agentUpdate(researchId, AGENT_IDS.ANALYZER, AGENT_STATES.COMPLETED,
      'analysis_complete',
      `Analysis complete. ${claims.length} claims verified. Sufficient evidence confirmed.`);
    await delay(700);

    await agentUpdate(researchId, AGENT_IDS.ORCHESTRATOR, AGENT_STATES.WORKING,
      'routing', 'Orchestrator: Evidence sufficient — routing to Writer to draft the paper.');
    await delay(600);

    await handoff(researchId, AGENT_IDS.ANALYZER, AGENT_IDS.WRITER,
      'Analyzer → Writer: Evidence verified. Begin drafting the research paper.');
  } else {
    // ══════════════════════════════════════════════════════════════════════
    // REAL MODE: AI Analyzer with Gemini 3.8 Flash & Agentic Feedback Loop
    // ══════════════════════════════════════════════════════════════════════
    const MAX_RESEARCH_PASSES = 3;
    let researchPass = 1;
    let currentClaims = [...initialClaims];
    let evaluations = [];

    while (researchPass <= MAX_RESEARCH_PASSES) {
      await agentUpdate(
        researchId,
        AGENT_IDS.ANALYZER,
        AGENT_STATES.VERIFYING,
        'evaluating_evidence',
        `Evaluating research claims against evidence with Gemini (Pass ${researchPass}/${MAX_RESEARCH_PASSES})...`
      );
      await delay(1200);

      const sessionSnap = getResearch(researchId);
      const allSourcesSoFar = sessionSnap?.sources ?? initialSources;

      // Analyze claims with Gemini 3.8 Flash
      try {
        evaluations = await analyzeClaims({
          topic,
          claims: currentClaims,
          sources: allSourcesSoFar,
        });
      } catch (analyzerErr) {
        console.error(`[AgentEngine] Analyzer failed in session ${researchId}:`, analyzerErr.message);
        await agentUpdate(
          researchId,
          AGENT_IDS.ANALYZER,
          AGENT_STATES.ERROR,
          'analysis_failed',
          analyzerErr.message
        );

        updateResearch(researchId, {
          status:       RESEARCH_STATUS.ERROR,
          currentAgent: null,
        });

        fire(researchId, {
          type:    EVENT_TYPES.ERROR,
          agent:   AGENT_IDS.ANALYZER,
          status:  AGENT_STATES.ERROR,
          action:  'analysis_error',
          message: analyzerErr.message,
          payload: { error: analyzerErr.message },
        });
        return;
      }

      const insufficientEvals = evaluations.filter((e) => e.status === 'insufficient');

      // Trigger feedback loop if evidence is insufficient and passes remain
      if (insufficientEvals.length > 0 && researchPass < MAX_RESEARCH_PASSES) {
        fire(researchId, {
          type:    EVENT_TYPES.INSUFFICIENT_EVIDENCE,
          agent:   AGENT_IDS.ANALYZER,
          status:  AGENT_STATES.VERIFYING,
          action:  'insufficient_evidence',
          message: `Insufficient evidence for ${insufficientEvals.length} claim(s). Requesting supplementary research.`,
          payload: {
            insufficientCount: insufficientEvals.length,
            claimId:           insufficientEvals[0]?.claimId,
            issue:             insufficientEvals[0]?.summary || 'Additional evidence required.',
          },
        });
        await delay(1000);

        // Orchestrator routes back to Researcher
        await agentUpdate(
          researchId,
          AGENT_IDS.ORCHESTRATOR,
          AGENT_STATES.WORKING,
          'rerouting',
          `Orchestrator: Insufficient evidence — rerouting to Researcher for supplementary pass (${researchPass + 1}/${MAX_RESEARCH_PASSES}).`
        );
        await delay(700);

        await handoff(
          researchId,
          AGENT_IDS.ANALYZER,
          AGENT_IDS.RESEARCHER,
          `Analyzer → Researcher: Search supplementary evidence for pass ${researchPass + 1}.`
        );

        // Researcher executes supplementary pass
        researchPass++;
        await agentUpdate(
          researchId,
          AGENT_IDS.RESEARCHER,
          AGENT_STATES.WORKING,
          'searching',
          `Searching scholarly sources for supplementary evidence (Pass ${researchPass})...`
        );
        await delay(1200);

        const currentSourcesSnap = getResearch(researchId)?.sources ?? [];
        const { sources: suppSources, claims: suppClaims = [] } = await providerSearch({
          topic,
          existingSources: currentSourcesSnap,
          pass: 'supplementary',
        });

        for (const suppSource of suppSources) {
          addSource(researchId, suppSource);
          fire(researchId, {
            type:    EVENT_TYPES.SOURCE_FOUND,
            agent:   AGENT_IDS.RESEARCHER,
            status:  AGENT_STATES.WORKING,
            action:  'source_found',
            message: `Found supplementary source: "${suppSource.title}"`,
            payload: suppSource,
          });
          await delay(700);
        }

        // Incorporate any supplementary claims and attach supplementary sources to pending claims
        for (const sc of suppClaims) {
          if (!currentClaims.some((c) => c.id === sc.id)) {
            currentClaims.push(sc);
          }
        }
        if (suppSources.length > 0) {
          for (const c of currentClaims) {
            if (!c.sourceIds || c.sourceIds.length === 0) {
              c.sourceIds = [suppSources[0].id];
            }
          }
        }

        await agentUpdate(
          researchId,
          AGENT_IDS.RESEARCHER,
          AGENT_STATES.COMPLETED,
          'search_complete',
          `Supplementary search complete. Located ${suppSources.length} additional source(s).`
        );
        await delay(700);

        await handoff(
          researchId,
          AGENT_IDS.RESEARCHER,
          AGENT_IDS.ANALYZER,
          'Researcher → Analyzer: Expanded source set ready for re-evaluation.'
        );
      } else {
        // Sufficient evidence obtained OR maximum passes reached
        break;
      }
    }

    // Finalize verified claims and broadcast canonical events
    await agentUpdate(
      researchId,
      AGENT_IDS.ANALYZER,
      AGENT_STATES.VERIFYING,
      'finalizing_analysis',
      'Finalizing claim evaluations and verifying evidence consistency...'
    );
    await delay(1000);

    const verifiedClaims = [];
    for (const evalItem of evaluations) {
      const claim = currentClaims.find((c) => c.id === evalItem.claimId) ?? {
        id: evalItem.claimId,
        text: `Claim evaluated for ${topic}`,
      };

      const updatedClaim = {
        ...claim,
        status:      evalItem.status,
        confidence:  evalItem.confidence,
        sourceIds:   evalItem.sourceIds || [],
        evidenceIds: evalItem.evidenceIds || claim.evidenceIds || [],
        summary:     evalItem.summary,
      };

      // Strict grounding: Never mark a claim supported if evidence or source count is 0
      if (updatedClaim.status === 'supported' && (updatedClaim.evidenceIds.length === 0 || updatedClaim.sourceIds.length === 0)) {
        updatedClaim.status = 'insufficient';
        updatedClaim.evidenceIds = [];
        updatedClaim.confidence = Math.min(updatedClaim.confidence || 0.45, 0.45);
        if (!updatedClaim.summary.toLowerCase().includes('insufficient')) {
          updatedClaim.summary = 'Insufficient direct evidence found in retrieved literature.';
        }
      }

      addClaim(researchId, updatedClaim);
      verifiedClaims.push(updatedClaim);

      if (updatedClaim.status === 'supported') {
        fire(researchId, {
          type:    EVENT_TYPES.CLAIM_VERIFIED,
          agent:   AGENT_IDS.ANALYZER,
          status:  AGENT_STATES.VERIFYING,
          action:  'claim_verified',
          message: `Claim verified (${Math.round(updatedClaim.confidence * 100)}% conf, ${updatedClaim.evidenceIds.length} evidence): "${(claim.text || '').substring(0, 80)}…"`,
          payload: {
            claimId:     updatedClaim.id,
            status:      'supported',
            confidence:  updatedClaim.confidence,
            sourceIds:   updatedClaim.sourceIds,
            evidenceIds: updatedClaim.evidenceIds,
            summary:     updatedClaim.summary,
          },
        });
      } else if (updatedClaim.status === 'conflict') {
        fire(researchId, {
          type:    EVENT_TYPES.CONFLICT_DETECTED,
          agent:   AGENT_IDS.ANALYZER,
          status:  AGENT_STATES.VERIFYING,
          action:  'conflict_detected',
          message: `Conflicting evidence detected: "${(claim.text || '').substring(0, 80)}…"`,
          payload: {
            claimId:     updatedClaim.id,
            status:      'conflict',
            confidence:  updatedClaim.confidence,
            sourceIds:   updatedClaim.sourceIds,
            evidenceIds: updatedClaim.evidenceIds,
            summary:     updatedClaim.summary,
          },
        });
      } else {
        fire(researchId, {
          type:    EVENT_TYPES.INSUFFICIENT_EVIDENCE,
          agent:   AGENT_IDS.ANALYZER,
          status:  AGENT_STATES.VERIFYING,
          action:  'insufficient_evidence_final',
          message: `Evidence remains insufficient for: "${(claim.text || '').substring(0, 80)}…"`,
          payload: {
            claimId:     updatedClaim.id,
            status:      'insufficient',
            confidence:  updatedClaim.confidence,
            sourceIds:   updatedClaim.sourceIds,
            evidenceIds: updatedClaim.evidenceIds,
            summary:     updatedClaim.summary,
          },
        });
      }
      await delay(700);
    }

    const supportedCount = verifiedClaims.filter((c) => c.status === 'supported').length;
    await agentUpdate(
      researchId,
      AGENT_IDS.ANALYZER,
      AGENT_STATES.COMPLETED,
      'analysis_complete',
      `Analysis complete. ${supportedCount}/${verifiedClaims.length} claims verified.`
    );
    await delay(700);

    // Orchestrator routes to Writer
    await agentUpdate(
      researchId,
      AGENT_IDS.ORCHESTRATOR,
      AGENT_STATES.WORKING,
      'routing',
      'Orchestrator: Evidence verified — routing to Writer to draft the paper.'
    );
    await delay(600);

    await handoff(
      researchId,
      AGENT_IDS.ANALYZER,
      AGENT_IDS.WRITER,
      'Analyzer → Writer: Evidence verified. Begin drafting the research paper.'
    );

    claims = verifiedClaims;
  }

  // ══════════════════════════════════════════════════════════════════════
  // STEP 6 — WRITER: first draft
  // ══════════════════════════════════════════════════════════════════════
  await agentUpdate(researchId, AGENT_IDS.WRITER, AGENT_STATES.WORKING,
    'drafting', 'Drafting the research paper from verified evidence...');
  await delay(1800);

  await agentUpdate(researchId, AGENT_IDS.WRITER, AGENT_STATES.WORKING,
    'structuring',
    'Structuring sections: Introduction, Findings, Analysis, Conclusion...');
  await delay(1400);

  const currentSession = getResearch(researchId);
  const allSources     = currentSession.sources;
  const draftPaper     = buildPaper(topic, allSources, claims, false, isDemo);
  setPaper(researchId, draftPaper);

  fire(researchId, {
    type:    EVENT_TYPES.PAPER_UPDATED,
    agent:   AGENT_IDS.WRITER,
    status:  AGENT_STATES.WORKING,
    action:  'paper_updated',
    message: 'Initial draft complete. Paper structure finalised.',
    payload: { sections: Object.keys(draftPaper), demo: isDemo },
  });
  await delay(800);

  await agentUpdate(researchId, AGENT_IDS.WRITER, AGENT_STATES.COMPLETED,
    'draft_complete', 'Initial draft complete. Forwarding to Reviewer.');
  await delay(700);

  await handoff(researchId, AGENT_IDS.WRITER, AGENT_IDS.REVIEWER,
    'Writer → Reviewer: Initial draft ready for review.');

  // ══════════════════════════════════════════════════════════════════════
  // STEP 7 — REVIEWER: first pass → revision required (feedback loop)
  // ══════════════════════════════════════════════════════════════════════
  await agentUpdate(researchId, AGENT_IDS.REVIEWER, AGENT_STATES.VERIFYING,
    'reviewing', 'Reviewing claims, citations, and consistency...');
  await delay(1400);

  await agentUpdate(researchId, AGENT_IDS.REVIEWER, AGENT_STATES.VERIFYING,
    'checking_citations', 'Checking citation coverage and claim support...');
  await delay(1200);

  // Intentional feedback loop #2 — revision required based on actual paper state
  const targetFindingNum = isDemo ? 3 : Math.min(3, Math.max(1, claims.length));
  const issueMsg = isDemo
    ? 'Finding 3 needs an explicit reference to the supplementary source.'
    : `Finding ${targetFindingNum} requires explicit citation verification.`;

  fire(researchId, {
    type:    EVENT_TYPES.REVISION_REQUIRED,
    agent:   AGENT_IDS.REVIEWER,
    status:  AGENT_STATES.VERIFYING,
    action:  'revision_required',
    message: isDemo
      ? 'One claim requires clearer supporting evidence.'
      : `Finding ${targetFindingNum} requires explicit citation verification.`,
    payload: {
      issue:    issueMsg,
      severity: 'minor',
    },
  });
  await delay(1000);

  // Orchestrator re-routes
  await agentUpdate(researchId, AGENT_IDS.ORCHESTRATOR, AGENT_STATES.WORKING,
    'rerouting',
    'Orchestrator: Revision required — rerouting to Writer for targeted revision.');
  await delay(600);

  await handoff(researchId, AGENT_IDS.REVIEWER, AGENT_IDS.WRITER,
    `Reviewer → Writer: Please strengthen Finding ${targetFindingNum} with explicit citation evidence.`);

  // ══════════════════════════════════════════════════════════════════════
  // STEP 8 — WRITER: revision
  // ══════════════════════════════════════════════════════════════════════
  await agentUpdate(researchId, AGENT_IDS.WRITER, AGENT_STATES.WORKING,
    'revising', 'Revising the paper based on reviewer feedback...');
  await delay(1400);

  await agentUpdate(researchId, AGENT_IDS.WRITER, AGENT_STATES.WORKING,
    'incorporating_feedback', `Incorporating reviewer feedback into Finding ${targetFindingNum}...`);
  await delay(1200);

  const revisedPaper = buildPaper(topic, allSources, claims, true, isDemo);
  setPaper(researchId, revisedPaper);

  fire(researchId, {
    type:    EVENT_TYPES.PAPER_UPDATED,
    agent:   AGENT_IDS.WRITER,
    status:  AGENT_STATES.WORKING,
    action:  'paper_updated',
    message: isDemo
      ? 'Paper revised. Finding 3 strengthened with supplementary evidence.'
      : `Paper revised. Finding ${targetFindingNum} strengthened with verified citation evidence.`,
    payload: { revisedSection: `findings[${targetFindingNum - 1}]`, demo: isDemo },
  });
  await delay(800);

  await agentUpdate(researchId, AGENT_IDS.WRITER, AGENT_STATES.COMPLETED,
    'revision_complete', 'Revision complete. Returning to Reviewer for final approval.');
  await delay(700);

  await handoff(researchId, AGENT_IDS.WRITER, AGENT_IDS.REVIEWER,
    'Writer → Reviewer: Revised paper ready for final review.');

  // ══════════════════════════════════════════════════════════════════════
  // STEP 9 — REVIEWER: final pass → approved
  // ══════════════════════════════════════════════════════════════════════
  await agentUpdate(researchId, AGENT_IDS.REVIEWER, AGENT_STATES.VERIFYING,
    'final_review', 'Performing final verification...');
  await delay(1400);

  // Final claim verifications: ONLY re-confirm claims that are actually supported with evidence!
  const supportedClaims = claims.filter(
    (c) => c.status === 'supported' && Array.isArray(c.evidenceIds) && c.evidenceIds.length > 0
  );
  for (const claim of supportedClaims.slice(0, 2)) {
    fire(researchId, {
      type:    EVENT_TYPES.CLAIM_VERIFIED,
      agent:   AGENT_IDS.REVIEWER,
      status:  AGENT_STATES.VERIFYING,
      action:  'final_claim_verified',
      message: `Final verification passed: "${claim.text.substring(0, 80)}…"`,
      payload: {
        claimId:     claim.id,
        verifiedBy:  AGENT_IDS.REVIEWER,
        status:      'supported',
        evidenceIds: claim.evidenceIds,
        sourceIds:   claim.sourceIds,
      },
    });
    await delay(600);
  }

  const approvalMsg = supportedClaims.length > 0
    ? `Research paper approved with ${supportedClaims.length} verified claim(s). Citations and evidence validated.`
    : `Research paper finalized with provisional findings: retrieved literature provided insufficient empirical evidence to support key claims.`;

  await agentUpdate(researchId, AGENT_IDS.REVIEWER, AGENT_STATES.COMPLETED,
    'approved', approvalMsg);
  await delay(700);

  // Orchestrator closes the loop
  await agentUpdate(researchId, AGENT_IDS.ORCHESTRATOR, AGENT_STATES.COMPLETED,
    'workflow_complete', 'Research workflow complete. Paper approved and ready.');
  await delay(600);

  // Mark session completed
  updateResearch(researchId, {
    status:       RESEARCH_STATUS.COMPLETED,
    currentAgent: null,
  });

  // paper_completed — final event
  fire(researchId, {
    type:    EVENT_TYPES.PAPER_COMPLETED,
    agent:   AGENT_IDS.REVIEWER,
    status:  AGENT_STATES.COMPLETED,
    action:  'paper_completed',
    message: 'Research paper is complete and ready for viewing.',
    to:      null,
    payload: {
      researchId,
      topic,
      sourceCount: allSources.length,
      claimCount:  claims.length,
      status:      'completed',
      demo:        isDemo,
    },
  });
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Start the deterministic demo research workflow asynchronously.
 * Fire-and-forget — does NOT block the HTTP response.
 *
 * @param {string} researchId
 */
export function startDemoResearch(researchId) {
  const session = getResearch(researchId);
  if (!session) {
    console.warn(`[AgentEngine] Session ${researchId} not found — aborting.`);
    return;
  }

  // Intentionally NOT awaited — runs in the background
  runWorkflow(researchId, session.topic).catch((err) => {
    console.error(`[AgentEngine] Unhandled error in session ${researchId}:`, err.message);
    try {
      updateResearch(researchId, { status: RESEARCH_STATUS.ERROR });
      const event = createEvent({
        type:    EVENT_TYPES.ERROR,
        agent:   AGENT_IDS.ORCHESTRATOR,
        status:  AGENT_STATES.ERROR,
        action:  'engine_error',
        message: 'An internal error occurred in the agent engine.',
        payload: { error: err.message },
      });
      appendEvent(researchId, event);
      emit(researchId, event);
    } catch {
      // last-resort guard — never crash the Express server
    }
  });
}

export const startResearchWorkflow = startDemoResearch;
export { buildPaper, runWorkflow };
